services:
  web:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    env_file:
      - .env.sample
    volumes:
      - ./src:/app
    depends_on:
      - postgres
    links:
      - postgres
    
  postgres:
    image: postgres:14-alpine
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=12345678
        - POSTGRES_DB=abrigo_animais
    ports:
      - "5432:5432"
    