# Generated by Django 5.0.6 on 2024-05-20 22:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=250, verbose_name='Name'),
                ),
                ('age', models.IntegerField(verbose_name='Age')),
                (
                    'breed',
                    models.CharField(max_length=250, verbose_name='Breed'),
                ),
                (
                    'specie',
                    models.CharField(
                        choices=[
                            ('DOG', 'Dog'),
                            ('CAT', 'Cat'),
                            ('BIRD', 'Bird'),
                            ('RODENT', 'Rodent'),
                            ('OUTHER', 'Other'),
                        ],
                        default='OUTHER',
                        max_length=50,
                        verbose_name='Specie',
                    ),
                ),
                (
                    'size',
                    models.CharField(
                        choices=[
                            ('SMALL', 'Small'),
                            ('MEDIUM', 'Medium'),
                            ('LARGE', 'Large'),
                        ],
                        default='MEDIUM',
                        max_length=50,
                        verbose_name='Size',
                    ),
                ),
                ('weight', models.FloatField(verbose_name='Weight')),
                (
                    'photo',
                    models.ImageField(
                        upload_to='animals/', verbose_name='Photo'
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
            },
        ),
        migrations.CreateModel(
            name='CareModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                ('description', models.TextField(verbose_name='Description')),
                (
                    'care_type',
                    models.CharField(
                        choices=[
                            ('FOOD', 'Food'),
                            ('DRUG', 'Drug'),
                            ('OTHER', 'Other'),
                        ],
                        default='OTHER',
                        max_length=50,
                        verbose_name='Care type',
                    ),
                ),
                (
                    'animal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='shelter.animalmodel',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Care',
                'verbose_name_plural': 'Cares',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Responsible',
                'verbose_name_plural': 'Responsibles',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleContactModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('EMAIL', 'Email'),
                            ('PHONE', 'Phone'),
                            ('WHATSAPP', 'WhatsApp'),
                            ('OTHER', 'Other'),
                        ],
                        default='OTHER',
                        max_length=20,
                        verbose_name='Type',
                    ),
                ),
                (
                    'value',
                    models.CharField(max_length=250, verbose_name='Value'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
                (
                    'responsible',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contacts',
                        to='shelter.responsiblemodel',
                        verbose_name='Responsible',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Responsible Contact',
                'verbose_name_plural': 'Responsible Contacts',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleAddressModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'street',
                    models.CharField(max_length=250, verbose_name='Street'),
                ),
                (
                    'number',
                    models.CharField(max_length=20, verbose_name='Number'),
                ),
                (
                    'complement',
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name='Complement',
                    ),
                ),
                (
                    'neighborhood',
                    models.CharField(
                        max_length=250, verbose_name='Neighborhood'
                    ),
                ),
                (
                    'city',
                    models.CharField(max_length=250, verbose_name='City'),
                ),
                (
                    'state',
                    models.CharField(max_length=250, verbose_name='State'),
                ),
                (
                    'zip_code',
                    models.CharField(max_length=9, verbose_name='Zip code'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
                (
                    'responsible',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='addresses',
                        to='shelter.responsiblemodel',
                        verbose_name='Responsible',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Responsible Address',
                'verbose_name_plural': 'Responsible Addresses',
            },
        ),
        migrations.CreateModel(
            name='ShelterModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=250, verbose_name='Name'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Shelter',
                'verbose_name_plural': 'Shelters',
            },
        ),
        migrations.CreateModel(
            name='ShelterContactModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('EMAIL', 'Email'),
                            ('PHONE', 'Phone'),
                            ('WHATSAPP', 'WhatsApp'),
                            ('OTHER', 'Other'),
                        ],
                        default='OTHER',
                        max_length=20,
                        verbose_name='Type',
                    ),
                ),
                (
                    'value',
                    models.CharField(max_length=250, verbose_name='Value'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
                (
                    'shelter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contacts',
                        to='shelter.sheltermodel',
                        verbose_name='Shelter',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Shelter Contact',
                'verbose_name_plural': 'Shelter Contacts',
            },
        ),
        migrations.CreateModel(
            name='ShelterAddressModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'street',
                    models.CharField(max_length=250, verbose_name='Street'),
                ),
                (
                    'number',
                    models.CharField(max_length=20, verbose_name='Number'),
                ),
                (
                    'complement',
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name='Complement',
                    ),
                ),
                (
                    'neighborhood',
                    models.CharField(
                        max_length=250, verbose_name='Neighborhood'
                    ),
                ),
                (
                    'city',
                    models.CharField(max_length=250, verbose_name='City'),
                ),
                (
                    'state',
                    models.CharField(max_length=250, verbose_name='State'),
                ),
                (
                    'zip_code',
                    models.CharField(max_length=9, verbose_name='Zip code'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
                (
                    'shelter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='addresses',
                        to='shelter.sheltermodel',
                        verbose_name='Shelter',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Shelter Address',
                'verbose_name_plural': 'Shelter Addresses',
            },
        ),
    ]
