# Generated by Django 5.0.6 on 2024-05-18 17:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=250, verbose_name='Name'),
                ),
                ('age', models.IntegerField(verbose_name='Age')),
                (
                    'breed',
                    models.CharField(max_length=250, verbose_name='Breed'),
                ),
                (
                    'specie',
                    models.CharField(max_length=250, verbose_name='Specie'),
                ),
                (
                    'size',
                    models.CharField(
                        choices=[
                            ('SMALL', 'Small'),
                            ('MEDIUM', 'Medium'),
                            ('LARGE', 'Large'),
                        ],
                        default='MEDIUM',
                        max_length=50,
                        verbose_name='Size',
                    ),
                ),
                ('weight', models.FloatField(verbose_name='Weight')),
                (
                    'photo',
                    models.ImageField(
                        upload_to='animals/', verbose_name='Photo'
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
            },
        ),
        migrations.CreateModel(
            name='CareModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                ('description', models.TextField(verbose_name='Description')),
                (
                    'care_type',
                    models.CharField(
                        choices=[
                            ('FOOD', 'Food'),
                            ('DRUG', 'Drug'),
                            ('OTHER', 'Other'),
                        ],
                        default='OTHER',
                        max_length=50,
                        verbose_name='Care type',
                    ),
                ),
                (
                    'animal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='shelter.animalmodel',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Care',
                'verbose_name_plural': 'Cares',
            },
        ),
    ]
