# Generated by Django 5.0.6 on 2024-05-20 23:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                            ('canceled', 'Canceled'),
                        ],
                        default='pending',
                        max_length=50,
                    ),
                ),
                (
                    'animal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='shelter.animalmodel',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'responsible',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='shelter.responsiblemodel',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Adoption',
                'verbose_name_plural': 'Adoptions',
            },
        ),
    ]
