# Generated by Django 5.0.6 on 2024-05-25 14:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_adoptionmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='shelter',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='shelter.sheltermodel',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheltermodel',
            name='description',
            field=models.TextField(default=None, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheltermodel',
            name='photo',
            field=models.ImageField(
                upload_to='shelters/', verbose_name='Photo'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheltermodel',
            name='website',
            field=models.URLField(default=None, verbose_name='Website'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PartnerModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=250, verbose_name='Name'),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, null=True, verbose_name='Description'
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'shelter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='shelter.sheltermodel',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerContactModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('EMAIL', 'Email'),
                            ('PHONE', 'Phone'),
                            ('WHATSAPP', 'WhatsApp'),
                            ('OTHER', 'Other'),
                        ],
                        default='OTHER',
                        max_length=20,
                        verbose_name='Type',
                    ),
                ),
                (
                    'value',
                    models.CharField(max_length=250, verbose_name='Value'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
                (
                    'partner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contacts',
                        to='shelter.partnermodel',
                        verbose_name='Partner',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Partner Contact',
                'verbose_name_plural': 'Partner Contacts',
            },
        ),
        migrations.CreateModel(
            name='PartnerAddressModel',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created at'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Updated at'
                    ),
                ),
                (
                    'street',
                    models.CharField(max_length=250, verbose_name='Street'),
                ),
                (
                    'number',
                    models.CharField(max_length=20, verbose_name='Number'),
                ),
                (
                    'complement',
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name='Complement',
                    ),
                ),
                (
                    'neighborhood',
                    models.CharField(
                        max_length=250, verbose_name='Neighborhood'
                    ),
                ),
                (
                    'city',
                    models.CharField(max_length=250, verbose_name='City'),
                ),
                (
                    'state',
                    models.CharField(max_length=250, verbose_name='State'),
                ),
                (
                    'zip_code',
                    models.CharField(max_length=9, verbose_name='Zip code'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_created_by',
                        related_query_name='%(app_label)s_%(class)ss_created_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_updated_by',
                        related_query_name='%(app_label)s_%(class)ss_updated_by',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
                (
                    'partner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='addresses',
                        to='shelter.partnermodel',
                        verbose_name='Partner',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Partner Address',
                'verbose_name_plural': 'Partner Addresses',
            },
        ),
    ]
